### ISSUE TITLE
你好，您的红旅动漫的api接口文档访问不了了

### ISSUE THREAD

**Issue by linhaosheng** [tomoya92/hltmapp-mui#1]
你好，您的红旅动漫的api接口文档访问不了了

**Comment by atjiu** [comment]
可能是阿里云服务器的问题，我部署在上面的服务都访问不了了
我的个人主页，博客，bbs，so都访问不了，等等吧

**Comment by linhaosheng** [comment]
恩好的，谢谢你的接口文档，我把你的接口文档写成了android版，希望您不要介意

2016-08-24 

lin1282634597 

发件人：朋也 notifications@github.com
发送时间：2016-08-24 22:18
主题：Re: [tomoya92/hltmapp-mui] 你好，您的红旅动漫的api接口文档访问不了了 (#1)
收件人："tomoya92/hltmapp-mui"hltmapp-mui@noreply.github.com
抄送："linhaosheng"lin1282634597@163.com,"Author"author@noreply.github.com

可能是阿里云服务器的问题，我部署在上面的服务都访问不了了
我的个人主页，博客，bbs，so都访问不了，等等吧

**Comment by atjiu** [comment]
你是开发了一个安卓原生的红旅动漫APP吗？

**Comment by linhaosheng** [comment]
恩，目前正在开发过程中

2016-08-24 

lin1282634597 

发件人：朋也 notifications@github.com
发送时间：2016-08-24 22:35
主题：Re: [tomoya92/hltmapp-mui] 你好，您的红旅动漫的api接口文档访问不了了 (#1)
收件人："tomoya92/hltmapp-mui"hltmapp-mui@noreply.github.com
抄送："linhaosheng"lin1282634597@163.com,"Author"author@noreply.github.com

你是开发了一个安卓原生的红旅动漫APP吗？

**Comment by atjiu** [comment]
服务器被攻击了，我重启了下，服务都起好了

开发好了记得给我一个下载地址啊，体验体验 : )

**Comment by linhaosheng** [comment]
恩，好的

2016-08-24 

lin1282634597 

发件人：朋也 notifications@github.com
发送时间：2016-08-24 23:07
主题：Re: [tomoya92/hltmapp-mui] 你好，您的红旅动漫的api接口文档访问不了了 (#1)
收件人："tomoya92/hltmapp-mui"hltmapp-mui@noreply.github.com
抄送："linhaosheng"lin1282634597@163.com,"Author"author@noreply.github.com

服务器被攻击了，我重启了下，服务都起好了
开发好了记得给我一个下载地址啊，体验体验 : )

**Comment by linhaosheng** [comment]
您好，请问您的红旅动漫的api接口文档里面的一周更新里获取到的json数据里面的list中的url 当访问时有api可以获取到它的json数据吗

2016-08-27 

lin1282634597 

发件人：朋也 notifications@github.com
发送时间：2016-08-24 22:35
主题：Re: [tomoya92/hltmapp-mui] 你好，您的红旅动漫的api接口文档访问不了了 (#1)
收件人："tomoya92/hltmapp-mui"hltmapp-mui@noreply.github.com
抄送："linhaosheng"lin1282634597@163.com,"Author"author@noreply.github.com

你是开发了一个安卓原生的红旅动漫APP吗？

**Comment by linhaosheng** [comment]
哦，我知道怎么获取了

2016-08-27 

lin1282634597 

发件人：朋也 notifications@github.com
发送时间：2016-08-24 23:07
主题：Re: [tomoya92/hltmapp-mui] 你好，您的红旅动漫的api接口文档访问不了了 (#1)
收件人："tomoya92/hltmapp-mui"hltmapp-mui@noreply.github.com
抄送："linhaosheng"lin1282634597@163.com,"Author"author@noreply.github.com

服务器被攻击了，我重启了下，服务都起好了
开发好了记得给我一个下载地址啊，体验体验 : )

**Comment by shiningrise** [comment]
```
        <% _.each(list, function(v, i){ %>
        <div class="mui-slider-item">
            <a href="javascript:;" data-url="<%=v.url%>">
                <img src="<%=v.img%>">
                <p class="mui-slider-title">
                    <%=v.title%>
                </p>
            </a>
        </div>
        <% }) %>
```

html页面，怎么像asp一样写代码，，我看不懂了，请高手，稍微指点下。

**Comment by atjiu** [comment]
@shiningrise 这用的是underscore.js，是一个js的模版，你去看看这个模版就知道了http://www.bootcss.com/p/underscore/

**Comment by shiningrise** [comment]
这是把后台程序写在前台中了，ui 与 js 没有分离，我觉得不是好的架构
比起angular 有什么优势？

**Comment by atjiu** [comment]
@shiningrise angular不熟，我懒得写原生的js，就用了这个模版库
