### ISSUE TITLE
你好，你的红旅动漫的新闻列表的api获取的数据是乱码的

### ISSUE THREAD

**Issue by linhaosheng** [tomoya92/hltmapp-mui#2]
你好，你的红旅动漫的新闻列表的api获取的数据是乱码的

**Comment by atjiu** [comment]
新闻列表的编码是charset=gb2312，我看能修一下不

**Comment by atjiu** [comment]
修好了

**Comment by linhaosheng** [comment]
您好，请问您的红旅动漫的api接口文档里面的一周更新里获取到的json数据里面的list中的url 当访问时有api可以获取到它的json数据吗

2016-09-02 

lin1282634597 

发件人：朋也 notifications@github.com
发送时间：2016-09-02 14:39
主题：Re: [tomoya92/hltmapp-mui] 你好，你的红旅动漫的新闻列表的api获取的数据是乱码的 (#2)
收件人："tomoya92/hltmapp-mui"hltmapp-mui@noreply.github.com
抄送："linhaosheng"lin1282634597@163.com,"Author"author@noreply.github.com

修好了

**Comment by atjiu** [comment]
没明月你的意思

**Comment by linhaosheng** [comment]
就是api中的https://hltm-api.tomoya.cn/weekUpdate 中获取到的json数据中的list集合里面的url，当我访问这个url时怎么获取到json数据

2016-09-02 

lin1282634597 

发件人：朋也 notifications@github.com
发送时间：2016-09-02 15:03
主题：Re: [tomoya92/hltmapp-mui] 你好，你的红旅动漫的新闻列表的api获取的数据是乱码的 (#2)
收件人："tomoya92/hltmapp-mui"hltmapp-mui@noreply.github.com
抄送："linhaosheng"lin1282634597@163.com,"Author"author@noreply.github.com

没明月你的意思

**Comment by atjiu** [comment]
就是搜索接口，你看看url，跟搜索接口是一样的

**Comment by linhaosheng** [comment]
您好，您的红旅动漫的api中的新闻列表详情不可用了，请问您可以修复一下吗
2016-09-15

lin1282634597

**Comment by atjiu** [comment]
@linhaosheng 回去我看看

**Comment by linhaosheng** [comment]
好的，谢谢

2016-09-15 

lin1282634597 

发件人：朋也 notifications@github.com
发送时间：2016-09-15 16:52
主题：Re: [tomoya92/hltmapp-mui] 你好，你的红旅动漫的新闻列表的api获取的数据是乱码的 (#2)
收件人："tomoya92/hltmapp-mui"hltmapp-mui@noreply.github.com
抄送："linhaosheng"lin1282634597@163.com,"Mention"mention@noreply.github.com

@linhaosheng 回去我看看
