### ISSUE TITLE
接口地址连不上

### ISSUE THREAD

**Issue by zhanghtt** [tomoya92/hltmapp-mui#6]
接口地址连不上

**Comment by atjiu** [comment]
@zhanghtt 接口项目是这个 https://github.com/tomoya92/hltm-api ，用nodejs写的，已经作了说明了

> 红旅网站改版比较大，这些接口大部分可能没用了，大家不要再用了，这个项目就当作一个nodejs抓取网站并解析的DEMO供大家参考

不好意思，现在已经不维护了
