### ISSUE TITLE
你只发布了安卓版本么？

### ISSUE THREAD

**Issue by LikeSpeedSong** [tomoya92/hltmapp-mui#7]

**Comment by atjiu** [comment]
@LikeSpeedSong 这个项目的接口已经没有维护了，请不要下载使用，仅作为学习mui的例子

另外，没有ios证书，打不了ios的包

**Comment by LikeSpeedSong** [comment]
我就是下载看看 我运行在我手机上发觉接口不行了 好可惜哇

**Comment by atjiu** [comment]
@LikeSpeedSong 在学mui？为啥不学react-native呢？如果要学react-native的话，可以看看我的另一个开源项目 https://github.com/tomoya92/ITNews-React-Native

**Comment by LikeSpeedSong** [comment]
RN 学习成本高一点，感谢你这么热情的回复我啊
